# Generated by Django 4.0.3 on 2022-04-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='commission',
        ),
        migrations.AddField(
            model_name='careers',
            name='amount_of_subjects',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
