# Generated by Django 4.0.3 on 2022-04-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_careers_commission_careers_amount_of_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='degree_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
